# Generated by Django 6.0.2 on 2026-03-05 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("progress", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decks", models.PositiveSmallIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("auto", "Automatic"), ("manual", "Manual")],
                        max_length=16,
                    ),
                ),
                (
                    "speed_tier",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("expert", "Expert"),
                        ],
                        max_length=16,
                    ),
                ),
                ("target_duration_ms", models.PositiveIntegerField()),
                ("hidden_cards_count", models.PositiveSmallIntegerField()),
                ("visible_cards_count", models.PositiveSmallIntegerField()),
                ("hidden_cards", models.JSONField(blank=True, default=list)),
                ("actual_running_count", models.IntegerField()),
                ("submitted_running_count", models.IntegerField(blank=True, null=True)),
                ("count_delta", models.IntegerField(blank=True, null=True)),
                ("is_correct", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("xp_delta", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
