# Generated by Django 6.0.2 on 2026-03-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("decks_per_shoe", models.PositiveSmallIntegerField()),
                ("hands_dealt", models.PositiveSmallIntegerField()),
                ("shoes_per_session", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("exited", "Exited"),
                            ("aborted", "Aborted"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_time_ms", models.PositiveIntegerField(default=0)),
                ("rounds_played", models.PositiveIntegerField(default=0)),
                ("rounds_with_correct_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Round",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.PositiveIntegerField()),
                ("shoe_index", models.PositiveIntegerField(default=1)),
                ("bet_amount", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("win", "Win"),
                            ("loss", "Loss"),
                            ("push", "Push"),
                            ("blackjack", "Blackjack"),
                        ],
                        default="push",
                        max_length=16,
                    ),
                ),
                ("net_chips_delta", models.IntegerField(default=0)),
                ("basic_strategy_correct", models.BooleanField(default=False)),
                ("user_action_taken", models.CharField(blank=True, max_length=16)),
                ("correct_action", models.CharField(blank=True, max_length=16)),
                ("dealer_upcard", models.CharField(max_length=4)),
                ("player_starting_hand", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="RoundCountSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_running_count_input", models.IntegerField()),
                ("actual_running_count", models.IntegerField()),
                ("is_correct", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
