# Generated by Django 6.0.2 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gameplay", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="starting_chips_balance",
            field=models.IntegerField(default=500),
        ),
    ]
