# Generated by Django 6.0.2 on 2026-03-02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="selected_deck_skin",
            field=models.CharField(
                choices=[
                    ("classic_red", "Classic Red"),
                    ("ocean_blue", "Ocean Blue"),
                    ("obsidian", "Obsidian"),
                    ("emerald", "Emerald"),
                    ("gold", "Gold"),
                ],
                default="classic_red",
                max_length=24,
            ),
        ),
    ]
